Workaround TF state issue.

diff --git a/.github/workflows/workers-testing-deployment.yaml b/.github/workflows/workers-testing-deployment.yaml
--- a/.github/workflows/workers-testing-deployment.yaml
+++ b/.github/workflows/workers-testing-deployment.yaml
@@ -191,6 +191,39 @@ jobs:
               sleep 60
             fi
           done
+      # This is a HACKY workaround.  It's the best bad solution we have come up with.
+      # https://github.com/akamai/terraform-provider-akamai/issues/560    
+      - name: Get Akamai Property ID
+        run: |
+          PROPERTY_ID=$(tofu output -raw akamai_property_id)
+          echo "Property ID: $PROPERTY_ID"
+          if [ -z "$PROPERTY_ID" ]; then
+            echo "Property ID is empty"
+            exit 1
+          fi
+        working-directory: terraform
+
+      - name: Resync TF State for Property
+        run: |
+          # Backup the current Terraform state
+          tofu state pull > backup.tfstate
+
+          # Get the Akamai property ID from the Terraform output
+          PROPERTY_ID=$(tofu output -raw akamai_property_id)
+
+          # Remove the existing resource from the state
+          tofu state rm akamai_property.my-property
+
+          # Attempt to use the property ID in the terraform import command
+          # Ensure that the address and ID are correctly specified as per the 'tofu import' command's expectation
+          if ! tofu import akamai_property.my-property $PROPERTY_ID; then
+            echo "Import failed, restoring the original state..."
+            tofu state push backup.tfstate
+          else
+            echo "Import succeeded."
+          fi
+        working-directory: terraform
+  
   # This job is designed to run when a branch is deleted, or a PR is closed or merged.  It will run tofu destroy to tear-down any resources created earlier. 
   cleanup:
     if: github.event_name == 'delete' || github.event.action == 'closed'
